Repository GSG-G10/saydat-alard, pull requests merged in 2021-11, with the labels that each got.

#111 "antd" base theme customization.
  client/craco.config.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.less
  client/src/index.js
Labels: Awaiting Review, Front end

#112 Data base insert
  server/package-lock.json
  server/package.json
  server/src/controllers/errors/errors.js
  server/src/controllers/main/getMainCities.js
  server/src/controllers/middlewares/asyncHandler.js
  server/src/controllers/middlewares/index.js
  server/src/controllers/middlewares/setCookie.js
  server/src/controllers/utilities/signupValidation.js
  server/src/database/config/build.js
  server/src/database/config/build.sql
  server/src/database/config/connection.js
  server/src/database/config/data.sql
  server/src/database/config/insertTables.js
  server/src/database/data/cities.json
  server/src/database/data/proverbs.json
  server/src/database/data/villages.json
  server/src/database/queries/addNewUser.js
  server/src/helpers/FailureResponse.js
  server/src/helpers/SuccessResponse.js
  server/src/helpers/httpResponse.js
  server/src/helpers/index.js
  server/src/routes/index.js
Labels: Awaiting Review, Back end

#107 Customize response
  server/src/app.js
  server/src/controllers/Auth/login.js
  server/src/controllers/Auth/signup.js
  server/src/controllers/Auth/userInfo.js
  server/src/controllers/city/cityData.js
  server/src/controllers/city/deleteStory.js
  server/src/controllers/city/getFamilies.js
  server/src/controllers/city/story.js
  server/src/controllers/city/updateStory.js
  server/src/controllers/dashboard/addCity.js
  server/src/controllers/dashboard/addProverb.js
  server/src/controllers/dashboard/approvedStory.js
  server/src/controllers/dashboard/deleteCityDashboard.js
  server/src/controllers/dashboard/deleteProvebDashboard.js
  server/src/controllers/dashboard/editCityData.js
  server/src/controllers/dashboard/editProvebDashboard.js
  server/src/controllers/dashboard/getDashboardCities.js
  server/src/controllers/dashboard/getDashboardProverbs.js
  server/src/controllers/dashboard/getDashboardStories.js
  server/src/controllers/errors/errors.js
  server/src/controllers/index.js
  server/src/controllers/main/getCitiesNames.js
  server/src/controllers/main/getMainCities.js
  server/src/controllers/main/getProverbs.js
  server/src/controllers/middlewares/asyncSignup.js
  server/src/controllers/middlewares/auth.js
  server/src/controllers/middlewares/checkUserExist.js
  server/src/controllers/middlewares/index.js
  server/src/controllers/middlewares/setCookie.js
  server/src/controllers/utilities/index.js
  server/src/controllers/utilities/loginSchema.js
  server/src/controllers/utilities/signupValidation.js
  server/src/database/config/data.sql
  server/src/database/queries/checkEmail.js
  server/src/database/queries/cityPage/addStoryQuery.js
  server/src/database/queries/cityPage/getUserIdQuery.js
  server/src/database/queries/cityPage/updateStoryQuery.js
  server/src/database/queries/dashboard/addNewCityQuery.js
  server/src/database/queries/dashboard/approverdStory.js
  server/src/database/queries/dashboard/editCityQuery.js
  server/src/helpers/FailureResponse.js
  server/src/helpers/boomHandler.js
  server/src/helpers/httpResponse.js
  server/src/helpers/index.js
  server/src/routes/authentication.js
  server/src/routes/city.js
  server/src/routes/dashboard.js
  server/src/routes/index.js
  server/src/routes/userStory.js
Labels: Awaiting Review, Back end

#116 36 image componenet
  client/package.json
  client/src/components/common/Img.jsx
Labels: Awaiting Review, Front end

#117 Btn Componenet
  client/package.json
  client/src/components/common/Button.jsx
Labels: Awaiting Review, Front end

#115 38 footer
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/components/common/CityInformation.jsx
  client/src/components/common/Footer/index.js
  client/src/components/common/Footer/style.css
  client/src/index.css
  client/src/index.js
Labels: Awaiting Review

#119 Paragraph componenet
  client/src/components/common/Paragraph.jsx
Labels: Done, Front end

#118 44 title component
  client/package.json
  client/src/components/common/Title.jsx
Labels: Awaiting Review, Front end

#121 handle searchSelect input
  client/package.json
  client/public/key.png
  client/src/components/common/Search.jsx
  client/src/components/common/css/search.css
  client/src/pages/City.jsx
  client/src/services/config.json
  client/src/services/errorAlert.js
  client/src/services/httpService.js
Labels: Awaiting Review, Front end, Common component

#124 scroll spy
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/common/ScrollSpy/ScrollSpy.jsx
  client/src/components/common/ScrollSpy/scrollSpy.css
  client/src/pages/City.jsx
Labels: Awaiting Review, Front end

#130 story Card
  client/.env~bee039bd8299e283042c3dea914a25893c744929
  client/package-lock.json
  client/package.json
  client/src/App/index.js
  client/src/components/common/Story/index.jsx
  client/src/components/common/Story/story.css
  client/src/context/AuthContext.jsx
  client/src/context/CityContext.jsx
  client/src/index.js
  client/src/pages/City.jsx
  server/src/database/config/data.sql
Labels: Awaiting Review, Front end, Common component

#129 50 background
  client/package-lock.json
  client/src/components/BackgroundImg.jsx
  client/src/components/city.css
  client/src/components/common/Paragraph.jsx
  client/src/components/common/ScrollSpy/ScrollSpy.jsx
  client/src/components/common/Title.jsx
  client/src/pages/City.jsx
Labels: Awaiting Review

#131 Add Proverb
  client/craco.config.js
  client/src/App/App.less
  client/src/App/index.js
  client/src/components/Proverbs/index.jsx
Labels: Awaiting Review

#127 49 signup
  .gitignore
  client/public/map.png
  client/src/App/index.js
  client/src/context/AuthContext.jsx
  client/src/pages/signup/SignUp.jsx
  client/src/pages/signup/SignupForm.jsx
  client/src/pages/signup/signup.css
  server/src/controllers/Auth/signup.js
Labels: Changes Requested

#132 Log In
  client/package.json
  client/src/App/index.js
  client/src/context/AuthContext.jsx
  client/src/pages/Login.jsx
  client/src/pages/login/index.jsx
  client/src/pages/login/login.css
  client/src/utils/images/flower.png
  server/src/controllers/Auth/login.js
Labels: Awaiting Review

#134 who are we section in main page
  client/src/components/sections/whoAreWe/index.jsx
  client/src/components/sections/whoAreWe/map.jpg
  client/src/components/sections/whoAreWe/style.css
  client/src/pages/Home.jsx
Labels: Changes Requested, Front end

#122 51 city information
  client/package-lock.json
  client/src/App/index.js
  client/src/components/common/BackgroundImg.jsx
  client/src/components/common/CityInformation.jsx
  client/src/context/AuthContext.jsx
  client/src/pages/City/City.jsx
  client/src/pages/City/City.jsx~HEAD
  client/src/pages/City/CityInformation.jsx
  client/src/pages/City/city.css
  client/src/pages/signup/SignupForm.jsx
  client/src/pages/signup/style.css
  client/src/utils/images/key.png
  client/src/utils/images/map.png
  client/src/utils/images/saydat-al-ard.jpg
  client/src/utils/images/tree.png
  client/src/utils/images/tree1.png
  package-lock.json
Labels: Changes Requested

#125 Story form
  client/package-lock.json
  client/src/components/common/CityCard/style.css
  client/src/components/slider/index.js
  client/src/components/slider/style.module.css
  client/src/components/uploadStoryForm/index.js
  client/src/components/uploadStoryForm/styles.css
  client/src/index.css
  client/src/index.js
  client/src/pages/City/City.jsx
  client/src/utils/index.js
  server/src/app.js
  server/src/controllers/city/story.js
  server/src/controllers/main/getCitiesNames.js
  server/src/database/queries/cityPage/addStoryQuery.js
  server/src/database/queries/story/getCityStoryQuery.js
Labels: Awaiting Review, Front end

#126 Book
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/libro/img/oldpaper.jpg
  client/src/components/libro/index.jsx
  client/src/components/libro/libro.css
  client/src/index.js
  client/src/pages/Home.jsx
  package-lock.json
  package.json
Labels: In Progress

#136 47 book
  client/src/components/libro/index.jsx
  client/src/index.js
  client/src/pages/Home.jsx
Labels: Done

#137 40 nav bar
  client/.prettierrc
  client/package.json
  client/public/logo.png
  client/src/App/ProtectedRoute.jsx
  client/src/App/index.js
  client/src/components/common/CityCard/style.css
  client/src/components/common/NavBar/index.js
  client/src/components/common/NavBar/style.module.css
  client/src/components/slider/style.module.css
  client/src/context/AuthContext.jsx
  client/src/index.css
  client/src/pages/City/City.jsx
  client/src/pages/City/CityInformation.jsx
  client/src/pages/Home.jsx
  client/src/pages/Login.jsx
  client/src/pages/login/index.jsx
  client/src/pages/login/login.css
  client/src/utils/images/flower.png
  server/src/controllers/Auth/login.js
Labels: Awaiting Review, Front end

#138 City Page - Collected
  client/src/components/Story/index.jsx
  client/src/components/Story/style.css
  client/src/components/city.css
  client/src/components/common/Footer/style.css
  client/src/components/common/ScrollSpy/index.jsx
  client/src/components/common/ScrollSpy/style.css
  client/src/components/common/Story/index.jsx
  client/src/components/common/Story/story.css
  client/src/components/common/search/index.jsx
  client/src/components/common/search/style.css
  client/src/components/sections/whoAreWe/style.css
  client/src/components/slider/style.module.css
  client/src/components/uploadStoryForm/index.js
  client/src/context/CityContext.jsx
  client/src/pages/City/City.jsx
  client/src/pages/City/city.css
Labels: Changes Requested, Front end

#141 handle dashboard => form Add city
  client/craco.config.js
  client/public/index.html
  client/src/App/ProtectedRoute.jsx
  client/src/App/index.js
  client/src/components/addCityForm/index.jsx
  client/src/components/common/NavBar/index.js
  client/src/components/common/search/style.css
  client/src/context/AuthContext.jsx
  client/src/index.css
  client/src/pages/Dashboard.jsx
  client/src/pages/dashboard/city/City.jsx
  client/src/pages/dashboard/index.jsx
  client/src/pages/dashboard/style.css
  client/src/utils/images/kof.png
  client/src/utils/images/kofiya.png
Labels: Awaiting Review

#142 Delete and Add Story in pending story
  client/src/components/AddStory/Addstory.css
  client/src/components/AddStory/Addstory.jsx
  client/src/components/common/BackgroundImg.jsx
  client/src/components/common/Dashboard.jsx
Labels: Awaiting Review

#145 Main collect
  client/src/components/Proverbs/index.jsx
  client/src/components/addCityForm/index.jsx
  client/src/components/common/Footer/style.css
  client/src/components/common/search/index.jsx
  client/src/components/common/search/style.css
  client/src/components/libro/index.jsx
  client/src/components/libro/libro.css
  client/src/components/sections/whoAreWe/index.jsx
  client/src/components/sections/whoAreWe/style.css
  client/src/components/slider/index.js
  client/src/components/slider/style.css
  client/src/index.css
  client/src/pages/Home.jsx
  server/src/app.js
  server/src/controllers/main/getProverbs.js
  server/src/database/queries/getProverbQuery.js
Labels: Awaiting Review

#147 Edit project link
  README.md
Labels: Awaiting Review

#149 Error page
  client/src/App/index.js
  client/src/pages/Error.jsx
  client/src/pages/signup/style.css
Labels: Done

#150 Edit readme
  README.md
Labels: Done

#151 edit signup
  client/public/index.html
  client/public/saydat-al-ard.jpg
  client/src/pages/signup/SignupForm.jsx
Labels: Done

#146 Dash board cities
  README.md
  client/public/index.html
  client/public/saydat-al-ard.jpg
  client/src/components/Proverbs/index.jsx
  client/src/components/common/NavBar/index.js
  client/src/components/common/Navbar.jsx
  client/src/components/dashBoardCities/index.js
  client/src/components/dashBoardCities/style.module.css
  client/src/context/AuthContext.jsx
  client/src/pages/City/City.jsx
  client/src/pages/City/CityInformation.jsx
  client/src/pages/City/city.css
  client/src/pages/dashboard/index.jsx
  client/src/pages/signup/SignupForm.jsx
  server/src/controllers/dashboard/editCityData.js
  server/src/database/queries/dashboard/getDashboardCitiesQuery.js
  server/src/routes/dashboard.js
Labels: In Progress
