Repository GSG-G10/saydat-alard, pull requests merged in 2021-10, with the labels that each got.

#98 12 city and story
  server/src/controllers/city/cityData.js
  server/src/controllers/city/index.js
  server/src/controllers/index.js
  server/src/database/queries/cityPage/getCityDataQuery.js
  server/src/database/queries/cityPage/index.js
  server/src/database/queries/index.js
  server/src/database/queries/story/getCityStoryQuery.js
  server/src/database/queries/story/index.js
  server/src/routes/index.js
Labels: Changes Requested

#104 21 update city data
  package-lock.json
  package.json
  server/src/controllers/dashboard/editCityData.js
  server/src/controllers/dashboard/index.js
  server/src/controllers/index.js
  server/src/database/queries/dashboard/editCityQuery.js
  server/src/database/queries/dashboard/index.js
  server/src/database/queries/index.js
  server/src/routes/index.js
Labels: Changes Requested

#105 edit error messages
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  server/src/controllers/Auth/login.js
  server/src/controllers/Auth/signup.js
  server/src/controllers/city/deleteStory.js
  server/src/controllers/city/story.js
  server/src/controllers/city/updateStory.js
  server/src/controllers/dashboard/addCity.js
  server/src/controllers/dashboard/deleteCityDashboard.js
  server/src/controllers/dashboard/deleteProvebDashboard.js
  server/src/controllers/main/getMainCities.js
  server/src/controllers/main/getProverbs.js
  server/src/controllers/middlewares/auth.js
  server/src/controllers/middlewares/checkUserExist.js
  server/src/controllers/middlewares/isAdmin.js
  server/src/controllers/middlewares/setCookie.js
  server/src/controllers/utilities/loginSchema.js
  server/src/controllers/utilities/signupValidation.js
  server/src/controllers/utilities/signupValidation.js.js
  server/src/database/queries/addNewUser.js
Labels: Awaiting Review

#102 User info
  server/src/controllers/Auth/index.js
  server/src/controllers/Auth/userInfo.js
  server/src/controllers/index.js
  server/src/controllers/utilities/index.js
  server/src/database/queries/getUser.js
  server/src/routes/index.js
Labels: Awaiting Review, Back end
